# Form implementation generated from reading ui file '/home/shasarazade/Projects/Python/Noted/About.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(645, 423)
        Form.setWindowTitle("About Noted.")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleIcon = QtWidgets.QLabel(parent=Form)
        self.TitleIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.TitleIcon.setText("")
        self.TitleIcon.setPixmap(QtGui.QPixmap("/home/shasarazade/Projects/Python/Noted/icon250.png"))
        self.TitleIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.TitleIcon.setObjectName("TitleIcon")
        self.verticalLayout.addWidget(self.TitleIcon)
        self.Title = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(36)
        font.setBold(True)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title)
        self.Desc = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.Desc.setFont(font)
        self.Desc.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.Desc.setObjectName("Desc")
        self.verticalLayout.addWidget(self.Desc)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.Title.setText(_translate("Form", "Noted."))
        self.Desc.setText(_translate("Form", "Write down your note here!."))
        self.label.setText(_translate("Form", "This App is created by Yamaoba. With License of GNU SIGMA IDK WHAT I NEED TO WRITE"))
